const SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
const STATUSES = ['OPEN', 'TRIAGED', 'INVESTIGATING', 'MITIGATING', 'MONITORING', 'RESOLVED', 'POSTMORTEM']
const TERMINAL_STATUSES = ['RESOLVED', 'POSTMORTEM']

module.exports = { SEVERITIES, STATUSES, TERMINAL_STATUSES }
